if(EXISTS "/Users/kyoshitou/Documents/NYU/blockchain/CodeZKP/field_poly_tests[1]_tests.cmake")
  include("/Users/kyoshitou/Documents/NYU/blockchain/CodeZKP/field_poly_tests[1]_tests.cmake")
else()
  add_test(field_poly_tests_NOT_BUILT field_poly_tests_NOT_BUILT)
endif()
